# This is a basic workflow to help you get started with Actions

name: docs-deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ 09/12/2020 ]
  pull_request:
    branches: [ 09/12/2020 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs-1/"
        build-command: "sphinx-build -b html . _build"
